name: Push_Docker_image_to_ECR
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage:latest
    - name: Tag docker image
      run: docker tag myimage:latest ${{secrets.AWS_ECR_SERVER}}/demoecr:${{github.sha}}

    - name: ECR-login
      run: echo ${{secrets.AWS_ECR_TOKEN}} | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_SERVER}}

    - name: PUSH_TO_ECR
      run: docker push ${{secrets.AWS_ECR_SERVER}}/demoecr:${{github.sha}}

