on: [push]
name: Deploy_to_ACI_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDS_SP }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_LOGIN_NAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}aci-anils
            image: ${{ secrets.ACR_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            registry-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            registry-username: ${{ secrets.ACR_LOGIN_NAME }}
            registry-password: ${{ secrets.ACR_PASSWORD }}
            name: anil123aka
            location: 'west us'