name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AZURE_WEB_APP: 'github-actions-test-anilappari'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{secrets.ACR_LOGIN_SERVER}}'/my-image-name:latest

    - name: login to acr
      run: docker login -u '${{secrets.ACR_LOGIN_NAME}}' -p '${{secrets.ACR_PASSWORD}}' '${{secrets.ACR_LOGIN_SERVER}}'

    - name: push to ecr
      run: docker push '${{secrets.ACR_LOGIN_SERVER}}'/my-image-name:latest


    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS_SP }}

    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v2.2.3
      with: 
        app-name: github-actions-test-anilappari
        images: '${{secrets.ACR_LOGIN_SERVER}}/my-image-name:latest'

