name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AZURE_WEB_APP: 'github-actions-test-anilappari'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Official SonarQube Scan
    #   # You may pin to the exact commit or the version. https://github.com/SonarSource/sonarqube-scan-action
    #   # uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
    #   uses: SonarSource/sonarqube-scan-action@v1.1.0
    #   env:
    #       SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONARQUBE_SERVER_URL }}
    #   with:
    #     # Additional arguments to the sonar-scanner SONARQUBE_TOKEN SONARQUBE_SERVER_URL
    #     args: > 
    #       -Dsonar.projectKey=githubactions_test
    #     # Set the sonar.projectBaseDir analysis property
    #     projectBaseDir: # optional, default is .

    # - name: SonarQube Quality Gate check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   # Force to fail step after specific time
    #   timeout-minutes: 5
    #   env:
    #    SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage:latest

    - uses: azure/container-scan@v0 ##https://github.com/marketplace/actions/container-image-scan
      with: 
        image-name: myimage:latest

    - name: Tag the Docker image
      run: docker image tag myimage '${{secrets.ACR_LOGIN_SERVER}}'/my-image-name:$(git log -1 --format='%h)

    - name: login to acr
      run: docker login -u '${{secrets.ACR_LOGIN_NAME}}' -p '${{secrets.ACR_PASSWORD}}' '${{secrets.ACR_LOGIN_SERVER}}'

    - name: push to ecr
      run: docker push '${{secrets.ACR_LOGIN_SERVER}}'/my-image-name:$(git log -1 --format='%h)

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS_SP }}

    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v2.2.3
      with: 
        app-name: github-actions-test-anilappari
        images: '${{secrets.ACR_LOGIN_SERVER}}/my-image-name:$(git log -1 --format='%h)'

