name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ACR_LOGIN_SERVER}}/my-image-name:latest

    - name: login to acr
      run: docker login -u ${{ACR_LOGIN_NAME}} -p ${{ACR_PASSWORD}} ${{ACR_LOGIN_SERVER}}

    - name: push to ecr
      run: docker push ${{ACR_LOGIN_SERVER}}/my-image-name:latest
    
      
